[build]
  publish = "dist"
  command = "npm run build && ls dist/"

[build.environment]
  NODE_VERSION = "18.14.1"
  NPM_FLAGS = "--legacy-peer-deps"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"