[build]
  publish = "dist"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "18.14.1"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
